### ISSUE TITLE
filename manager is reusing file names after an epoch change

### ISSUE THREAD

**Issue by slfritchie** [basho/machi#36]
This bug was originally found by @shino's work on #33 ... that QuickCheck model is working!  Shino's QuickCheck model almost always finds this error within a couple of minutes.

Description of an actual counter-example:
- During epoch 1113, UPI=[a,b,c] ... and there is some data written to this file, and it is written successfully to all a,b,c.
- Then epoch changes to 1115.  B believes that UPI=[b].
- The first append to b, the epoch is different, so the filename_mgr uses the line 155 case, creates a new name (correctly, yay!).
- The _second append_ to b in epoch 1115, the handle_find_file() is ... looking on disk to find a file to append to, finds the the file written during epoch 1113, and uses it for this second append.  This is when Machi's eventual consistency "files are always mergeable" property fails.

In eventual consistency mode, the filename manager must always pick a new & unique file name after an epoch change.  In strong consistency mode, reuse after an epoch change is OK because we don't have the same merging requirement.

However, we'd still like to preserve the ability to append to a file after a period of inactivity.  The current implementation (which uses `filelib:wildcard()` and so needs a refactoring sometime for better efficiency) appears to do that AFAICT.  So a modification that can do the right thing with eventual mode + epoch change seems best?

**Comment by slfritchie** [comment]
An incorrect-in-the-wider-scheme-of-things patch can be found at https://gist.github.com/slfritchie/12e40859a08d5e4a678a ... further development of the new QuickCheck model can proceed using this workaround.

**Comment by kuenishi** [comment]
Including an epoch number or csum to a file name, to guarantee file mergability and prevent append to wrong file - running wildcard with it when assigning a filename might be one of choices? It would be good for current code as well as robust to process restart. Though I'm not sure how epoch csum is unique... Second option is to generate an unique UUID when an epoch number is incremented (or when a new epoch number is found), and use it during that epoch (currently is it generating uuid every time a file is created?). Every file name assignment must utilize that UUID. Two UUIDs in a file name could be too long, so maybe it's good time to dig a directory.

Also, I wasn't aware that current implementation of using file numbers as part of file name. This will be screwed up by trimming _a file_, where a file is deleted and it's name is just remembered in "known_files", esp after restarting a flu server (ets filenames cache will be cleared).

**Comment by jadeallenx** [comment]
The current file sequence number is stored on disk, so it should be safe to remove files that have been completely trimmed. I think ultimately we need to **not** use the wildcard function (I copied that bit of code from the FLU itself) but as for what we should replace that with I'm not certain - there are a lot of options that might work ok.

**Comment by shino** [comment]
Another dirty fix by adding FLU name between UUID and sequence number: https://github.com/basho/machi/commit/0e21581?w=1

**Comment by slfritchie** [comment]
I'm not sure if #43 is also related ... I told Mark yesterday that I was pretty sure that Shino's fix yesterday wouldn't be sufficient.  I haven't studied #43 very closely yet, sorry.

**Comment by shino** [comment]
Is #43 the same as #36 ? AFAIK, #36 is not fixed yet :sweat_smile:

**Comment by kuenishi** [comment]
I think the root cause of #43 is the same as this.

**Comment by shino** [comment]
Can this be closed as well as #43 ?

**Comment by slfritchie** [comment]
> Can this be closed as well as #43 ?

Yes, I believe so.  We can re-open this ticket if we've made a mistake.
